# Generated by Django 3.1.6 on 2021-02-11 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productions',
            name='file',
            field=models.FileField(default='', editable=False, upload_to='files/'),
        ),
    ]
