# Generated by Django 3.1.6 on 2021-02-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productions', '0002_productions_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productions',
            name='file',
            field=models.FileField(upload_to='files/', verbose_name='Excel File'),
        ),
    ]
